### ISSUE TITLE
Report version through /proc/cmdline

### ISSUE THREAD

**Issue by DylanVanAssche** [SHIFTPHONES/android_bootable_bootloader_edk2#2]
The hardware version is already reported in `/proc/cmdline` as `androidboot.hardware.revision=10001`, would be great to have the ABL version as well there: `androidboot.abl.revision=$major.$minor.$DATE`.

This naming scheme allows reporting other version information as well like XBL

**Comment by amartinz** [comment]
Submitted, as discussed on Matrix.
Thank you very much! :)

Will be shipped starting with SOS 3.9.
Any version below (if property does not exist) can be considered legacy and thus `currently installed < fwupd available` version.
